CREATE TABLE IF NOT EXISTS public.health_checks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_at timestamp with time zone DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.cleanup_health_checks()
RETURNS void AS $$
BEGIN
  DELETE FROM public.health_checks 
  WHERE id NOT IN (SELECT id FROM public.health_checks ORDER BY checked_at DESC LIMIT 20);
END;
$$ LANGUAGE plpgsql;
